name: CI - Test and Build Expo App

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test -- --ci --coverage

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Expo CLI
        run: npm install -g eas-cli

      - name: Login to Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Run EAS build for Android
        run: eas build --platform android --non-interactive

      - name: Run EAS build for iOS
        run: eas build --platform ios --non-interactive